name: palmoil
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.5
  - r-renv
  # FAPROTAX collapse_table.py is tested on Python 3.11 and requires NumPy.
  - python=3.11
  - numpy
  - libxml2
  - gsl
  - udunits2
  - glpk
  - zlib
  - bzip2
  - xz
